### ISSUE TITLE
Clicking the menu 'Tools' freezes the whole IDE

### ISSUE THREAD

**Issue by engiecat** [energia/Energia#826] opened 2016-01-19 05:15 UTC
Hello.

I am a user who recently returned to use Energia IDE.
However, one very critical problem renders the IDE unusable - clicking on the menu 'Tools' freezes the whole IDE for 1+ minutes, preventing me to select COM port and board type.

The version used is 0101E0017.
The OS I am using is Windows 10 Pro, and I am using i5-2467M CPU.
Arduino IDE is working very well on this machine.

**Comment by rei-vilo** [comment] 2016-01-19 07:13
The same issue used to happen with Arduino 1.0 Energia is based on. 

The delay is caused by the enumeration of all serial ports, including the Bluetooth ones. It could take up to 5 minutes. 

As a Window user, give [Visual Micro](http://www.visualmicro.com) a try. It's a free plug-in for Visual Studio and supports Energia.

**Comment by robertinant** [comment] 2016-01-19 17:32
The next release of Energia will be based on the latest and greatest Arduino IDE and this issue will be solved by moving to that new IDE. For this reason, it does not make sense for us to fix it in the current IDE.

**Closed by robertinant** 2016-01-19 17:32 UTC
Labels: IDE Energia, OS Windows, Sort Not Energia-Specific

**Comment by rei-vilo** [comment] 2016-01-19 17:33
See Update the IDE to release 1.6.7 of Arduino #588.
